replicaCount: 1

image:
  repository: ""
  tag: "latest"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: "verdict-app"
  annotations: {}

ingress:
  enabled: false

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  fsGroup: 10001

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault

secretId: "verdict/app/api-key"
awsRegion: "ap-south-1"
